### PR TITLE
V3.0.7 Update

### PR DESCRIPTION
**Pull request by tobychui**
- Fixed redirection enable bug 
- Fixed header tool user agent rewrite sequence 
- Optimized rate limit UI 
- Added HSTS and Permission Policy Editor
- Restructured docker container selector implementation for conditional compilations for Windows

From contributors
- Add Rate Limits Limits to Zoraxy #196 by @Kirari04
- Add docker containers list to set rules #202 by @7brend7

### CODE REVIEW

**Comment by tobychui** [comment]
@yeungalan I am not sure about your commits over the [EAB implementation done](https://github.com/tobychui/zoraxy/pull/208/commits/b1a14872c3fe7ce41e15606d4a2012422131b57e). Can you double check this is working with the latest ACME module commits?

@PassiveLemon The new version added a startup paramter for docker. I guess you might need to add `-docker=true` in your docker file. Thanks!

**Comment by PassiveLemon** [comment]
I will make the changes whenever I can

**Comment by PassiveLemon** [comment]
You should add the -docker flag to the main README

**Comment by tobychui** [comment]
Ok, cool. Next time remember to click the "finish review" buttons 👍🏻

**Pull request merged**
