### PR TITLE
Update Dockerfile to shrink image

### PR DESCRIPTION
**Pull request by Kegelcizer**
2.8 GB -> 383.2 MB
image
image

### CODE REVIEW

**Comment by tobychui** [comment]
Hi @Kegelcizer , thanks for the PR!
I will tag our docker maintainer @PassiveLemon and let him / her handle this PR from here.

**Comment by Kegelcizer** [comment]
Made it even smaller by targeting alpine 😆 
image

**Comment by PassiveLemon** [comment]
LGTM, however there's PR https://github.com/tobychui/zoraxy/pull/216 which already aims to do the same thing. I'll wait and see if that gets merged

**Comment by Kegelcizer** [comment]
Now that I've opened that PR, yes it does. Couldn't tell by the title.

**Pull request closed without merging**
